service: prana-core
frameworkVersion: '4'
configValidationMode: error
useDotenv: true

provider:
    name: aws
    runtime: nodejs24.x
    region: ${opt:region, env:AWS_REGION, 'us-east-1'}
    stage: ${opt:stage, env:STAGE, 'dev'}
    stackName: ${self:service}-${sls:stage}
    environment:
        APPOINTMENTS_TABLE_NAME: ${self:custom.appointmentsTableName}
        APPOINTMENT_TOPIC_ARN:
            Ref: AppointmentTopic
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:PutItem
                      - dynamodb:Query
                      - dynamodb:UpdateItem
                  Resource:
                      - Fn::GetAtt:
                            - AppointmentsTable
                            - Arn
                - Effect: Allow
                  Action:
                      - sns:Publish
                  Resource:
                      - Ref: AppointmentTopic
                - Effect: Allow
                  Action:
                      - events:PutEvents
                  Resource:
                      - Fn::GetAtt:
                            - AppointmentEventBus
                            - Arn

custom:
    appointmentsTableName: ${self:service}-${sls:stage}-appointments
    appointmentTopicName: ${self:service}-${sls:stage}-appointment-topic
    appointmentPeQueueName: ${self:service}-${sls:stage}-appointments-pe
    appointmentClQueueName: ${self:service}-${sls:stage}-appointments-cl
    appointmentCompletedQueueName: ${self:service}-${sls:stage}-appointments-completed
    appointmentEventBusName: prana-appointment-events
    appointmentCompletedRuleName: ${self:service}-${sls:stage}-appointment-completed

plugins:
    - serverless-offline

functions:
    appointment:
        handler: src/handlers/appointment/index.handler
        events:
            - httpApi:
                  path: /appointments
                  method: post
            - httpApi:
                  path: /appointments/{insuredId}
                  method: get
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - AppointmentCompletedQueue
                          - Arn
                  batchSize: 10
                  functionResponseType: ReportBatchItemFailures
    appointmentPe:
        name: ${self:service}-${sls:stage}-appointment-pe
        handler: src/handlers/appointmentPE.handler
        timeout: 10
        environment:
            MYSQL_HOST: ${env:MYSQL_HOST}
            MYSQL_PORT: ${env:MYSQL_PORT}
            MYSQL_USER: ${env:MYSQL_USER}
            MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}
            MYSQL_DATABASE_PE: ${env:MYSQL_DATABASE_PE}
            APPOINTMENT_EVENT_BUS_ARN:
                Fn::GetAtt:
                    - AppointmentEventBus
                    - Arn
        events:
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - AppointmentPeQueue
                          - Arn
                  batchSize: 10
                  functionResponseType: ReportBatchItemFailures
    appointmentCl:
        name: ${self:service}-${sls:stage}-appointment-cl
        handler: src/handlers/appointmentCL.handler
        timeout: 10
        environment:
            MYSQL_HOST: ${env:MYSQL_HOST}
            MYSQL_PORT: ${env:MYSQL_PORT}
            MYSQL_USER: ${env:MYSQL_USER}
            MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}
            MYSQL_DATABASE_CL: ${env:MYSQL_DATABASE_CL}
            APPOINTMENT_EVENT_BUS_ARN:
                Fn::GetAtt:
                    - AppointmentEventBus
                    - Arn
        events:
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - AppointmentClQueue
                          - Arn
                  batchSize: 10
                  functionResponseType: ReportBatchItemFailures

resources:
    Resources:
        AppointmentsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.appointmentsTableName}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: insuredId
                      AttributeType: S
                    - AttributeName: appointmentId
                      AttributeType: S
                KeySchema:
                    - AttributeName: insuredId
                      KeyType: HASH
                    - AttributeName: appointmentId
                      KeyType: RANGE
        AppointmentTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: ${self:custom.appointmentTopicName}
        AppointmentEventBus:
            Type: AWS::Events::EventBus
            Properties:
                Name: ${self:custom.appointmentEventBusName}
        AppointmentPeQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: ${self:custom.appointmentPeQueueName}
                VisibilityTimeout: 60
        AppointmentClQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: ${self:custom.appointmentClQueueName}
                VisibilityTimeout: 60
        AppointmentCompletedQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: ${self:custom.appointmentCompletedQueueName}
                VisibilityTimeout: 60
        AppointmentPeQueuePolicy:
            Type: AWS::SQS::QueuePolicy
            Properties:
                Queues:
                    - Ref: AppointmentPeQueue
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Sid: AllowAppointmentTopicToSendMessages
                          Effect: Allow
                          Principal:
                              Service: sns.amazonaws.com
                          Action:
                              - sqs:SendMessage
                          Resource:
                              - Fn::GetAtt:
                                    - AppointmentPeQueue
                                    - Arn
                          Condition:
                              ArnEquals:
                                  aws:SourceArn:
                                      Ref: AppointmentTopic
        AppointmentClQueuePolicy:
            Type: AWS::SQS::QueuePolicy
            Properties:
                Queues:
                    - Ref: AppointmentClQueue
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Sid: AllowAppointmentTopicToSendMessages
                          Effect: Allow
                          Principal:
                              Service: sns.amazonaws.com
                          Action:
                              - sqs:SendMessage
                          Resource:
                              - Fn::GetAtt:
                                    - AppointmentClQueue
                                    - Arn
                          Condition:
                              ArnEquals:
                                  aws:SourceArn:
                                      Ref: AppointmentTopic
        AppointmentCompletedQueuePolicy:
            Type: AWS::SQS::QueuePolicy
            Properties:
                Queues:
                    - Ref: AppointmentCompletedQueue
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Sid: AllowAppointmentCompletedRuleToSendMessages
                          Effect: Allow
                          Principal:
                              Service: events.amazonaws.com
                          Action:
                              - sqs:SendMessage
                          Resource:
                              - Fn::GetAtt:
                                    - AppointmentCompletedQueue
                                    - Arn
                          Condition:
                              ArnEquals:
                                  aws:SourceArn:
                                      Fn::GetAtt:
                                          - AppointmentCompletedRule
                                          - Arn
        AppointmentPeSubscription:
            Type: AWS::SNS::Subscription
            Properties:
                TopicArn:
                    Ref: AppointmentTopic
                Protocol: sqs
                Endpoint:
                    Fn::GetAtt:
                        - AppointmentPeQueue
                        - Arn
                RawMessageDelivery: false
                FilterPolicyScope: MessageAttributes
                FilterPolicy:
                    countryISO:
                        - PE
        AppointmentClSubscription:
            Type: AWS::SNS::Subscription
            Properties:
                TopicArn:
                    Ref: AppointmentTopic
                Protocol: sqs
                Endpoint:
                    Fn::GetAtt:
                        - AppointmentClQueue
                        - Arn
                RawMessageDelivery: false
                FilterPolicyScope: MessageAttributes
                FilterPolicy:
                    countryISO:
                        - CL
        AppointmentCompletedRule:
            Type: AWS::Events::Rule
            Properties:
                Name: ${self:custom.appointmentCompletedRuleName}
                EventBusName:
                    Ref: AppointmentEventBus
                State: ENABLED
                EventPattern:
                    source:
                        - prana.appointments
                    detail-type:
                        - AppointmentCompleted
                Targets:
                    - Id: AppointmentCompletedQueueTarget
                      Arn:
                          Fn::GetAtt:
                              - AppointmentCompletedQueue
                              - Arn
