service: prana-core
frameworkVersion: '4'
configValidationMode: error
useDotenv: true

provider:
    name: aws
    runtime: nodejs24.x
    region: ${opt:region, env:AWS_REGION, 'us-east-1'}
    stage: ${opt:stage, env:STAGE, 'dev'}
    stackName: ${self:service}-${sls:stage}
    environment:
        APPOINTMENTS_TABLE_NAME: ${self:custom.appointmentsTableName}
        APPOINTMENT_TOPIC_ARN:
            Ref: AppointmentTopic
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:PutItem
                      - dynamodb:Query
                  Resource:
                      - Fn::GetAtt:
                            - AppointmentsTable
                            - Arn
                - Effect: Allow
                  Action:
                      - sns:Publish
                  Resource:
                      - Ref: AppointmentTopic

custom:
    appointmentsTableName: ${self:service}-${sls:stage}-appointments
    appointmentTopicName: ${self:service}-${sls:stage}-appointment-topic
    appointmentPeQueueName: ${self:service}-${sls:stage}-appointments-pe
    appointmentClQueueName: ${self:service}-${sls:stage}-appointments-cl

plugins:
    - serverless-offline

functions:
    appointment:
        handler: src/handlers/appointment/index.handler
        events:
            - httpApi:
                  path: /appointments
                  method: post
            - httpApi:
                  path: /appointments/{insuredId}
                  method: get

resources:
    Resources:
        AppointmentsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.appointmentsTableName}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: insuredId
                      AttributeType: S
                    - AttributeName: appointmentId
                      AttributeType: S
                KeySchema:
                    - AttributeName: insuredId
                      KeyType: HASH
                    - AttributeName: appointmentId
                      KeyType: RANGE
        AppointmentTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: ${self:custom.appointmentTopicName}
        AppointmentPeQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: ${self:custom.appointmentPeQueueName}
        AppointmentClQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: ${self:custom.appointmentClQueueName}
        AppointmentPeQueuePolicy:
            Type: AWS::SQS::QueuePolicy
            Properties:
                Queues:
                    - Ref: AppointmentPeQueue
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Sid: AllowAppointmentTopicToSendMessages
                          Effect: Allow
                          Principal:
                              Service: sns.amazonaws.com
                          Action:
                              - sqs:SendMessage
                          Resource:
                              - Fn::GetAtt:
                                    - AppointmentPeQueue
                                    - Arn
                          Condition:
                              ArnEquals:
                                  aws:SourceArn:
                                      Ref: AppointmentTopic
        AppointmentClQueuePolicy:
            Type: AWS::SQS::QueuePolicy
            Properties:
                Queues:
                    - Ref: AppointmentClQueue
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        - Sid: AllowAppointmentTopicToSendMessages
                          Effect: Allow
                          Principal:
                              Service: sns.amazonaws.com
                          Action:
                              - sqs:SendMessage
                          Resource:
                              - Fn::GetAtt:
                                    - AppointmentClQueue
                                    - Arn
                          Condition:
                              ArnEquals:
                                  aws:SourceArn:
                                      Ref: AppointmentTopic
        AppointmentPeSubscription:
            Type: AWS::SNS::Subscription
            Properties:
                TopicArn:
                    Ref: AppointmentTopic
                Protocol: sqs
                Endpoint:
                    Fn::GetAtt:
                        - AppointmentPeQueue
                        - Arn
                RawMessageDelivery: false
                FilterPolicyScope: MessageAttributes
                FilterPolicy:
                    countryISO:
                        - PE
        AppointmentClSubscription:
            Type: AWS::SNS::Subscription
            Properties:
                TopicArn:
                    Ref: AppointmentTopic
                Protocol: sqs
                Endpoint:
                    Fn::GetAtt:
                        - AppointmentClQueue
                        - Arn
                RawMessageDelivery: false
                FilterPolicyScope: MessageAttributes
                FilterPolicy:
                    countryISO:
                        - CL
